### ISSUE TITLE
Add msgpack support

### ISSUE THREAD

**Issue by AlstonLin** [Yelp/bravado-core#214]
msgpack would be a more efficient way to receive large JSON body responses, and could mean large performance gains for people who want to use bravado with a server that supports `application/msgpack` responses

Support for this content type should be added to bravado

**Comment by AlstonLin** [comment]
@macisamuele For this functionality, one of the things I'd need to do is to add msgpack unmarshalling in bravado_core. However, to be able to do that I need to have access to the bytes of a response, which is currently not possible under the interface specified in `bravado_core.response.IncomingResponse`. So to implement this, I'd need to change IncomingResponse to have 'bytes' in the _required_attrs_, which would be a breaking change as now all implementations of this, including the `RequestsResponseAdapter` and `FidoResponseAdapter` in bravado will need to be updated to use the latest version of bravado_core if pushed. This means that this feature would require a breaking change to bravado_core. Would you say this is a feature worth having a breaking change?

**Comment by macisamuele** [comment]
@AlstonLin this is just to recap our quick chat 😄 
We can modify ``IncomingResponse`` in order to expose ``bytes`` other than ``text`` and ``json``, it should not be a breaking change but according to how it will be implemented, we can decide whenever is safe to go with a minor version bump or a major version bump.

I checked bravado-core and bravado implementations and those are the points that I would focus (it doesn't represent a limitation to you, it's more about giving ahead places to look in order to overcome the 9 hours gap):
 * modify [``bravado_core.response.IncomingResponse``](https://github.com/Yelp/bravado-core/blob/master/bravado_core/response.py#14) and [``bravado_core.response.OutgoingResponse``](https://github.com/Yelp/bravado-core/blob/master/bravado_core/response.py#56) in order to expose bytes
 * define a constant (like ``APP_JSON``) for handling msgpack content, update [``bravado_core.response.unmarshal_response``](https://github.com/Yelp/bravado-core/blob/master/bravado_core/response.py#L86)
 * we should update [``bravado.request_client.RequestResponseAdapter``](https://github.com/Yelp/bravado/blob/master/bravado/requests_client.py#L177), [``bravado.fido_client.FidoResponseAdapter``](https://github.com/Yelp/bravado/blob/master/bravado/fido_client.py#L21) and set minimum bravado-core dependency on bravado [setup.py](https://github.com/Yelp/bravado/blob/master/setup.py#L34)
 * we should update [``pyramid_swagger.tween.PyramidSwaggerRequest``](https://github.com/striglia/pyramid_swagger/blob/master/pyramid_swagger/tween.py#L204) and [``pyramid_swagger.tween. PyramidSwaggerResponse``](https://github.com/striglia/pyramid_swagger/blob/master/pyramid_swagger/tween.py#L274) in order to expose bytes and set minimum bravado-core dependency on pyramid-swagger

I'm pretty sure that I'm still missing something, but surely you'll figure it out 😄
